### Loading Raw Data ####

In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns

In [3]:
### Loading Raw Data ###
df = pd.read_csv("C:/Users/Sakthi/Downloads/ChargingRecords.csv")

In [ ]:
df.shape   ###.Inspect Row ,columns

(72856, 13)

In [6]:
df.head()

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
0,0,1,1,hotel,0,2022-09-15,20:54:02,2022-09-15,23:59:13,2022-09-15 20:54,2022-09-15 23:59,185,20.36
1,0,1,1,hotel,0,2022-09-14,20:01:05,2022-09-14,21:31:04,2022-09-14 20:01,2022-09-14 21:31,90,10.19
2,0,1,1,hotel,0,2022-09-14,18:54:30,2022-09-14,19:54:29,2022-09-14 18:54,2022-09-14 19:54,60,6.78
3,0,1,1,hotel,0,2022-09-29,18:32:51,2022-09-30,0:16:42,2022-09-29 18:32,2022-09-30 0:16,344,37.65
4,0,1,1,hotel,0,2022-09-25,19:30:15,2022-09-26,0:30:14,2022-09-25 19:30,2022-09-26 0:30,300,33.81

In [7]:
#### Check misising null values
df.isnull().sum()

UserID            0
ChargerID         0
ChargerCompany    0
Location          0
ChargerType       0
StartDay          0
StartTime         0
EndDay            0
EndTime           0
StartDatetime     0
EndDatetime       0
Duration          0
Demand            0
dtype: int64

In [ ]:
df.info()  ## Check data summary,column data type and memory usage

<class 'pandas.DataFrame'>
RangeIndex: 72856 entries, 0 to 72855
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   UserID          72856 non-null  int64
 1   ChargerID       72856 non-null  int64
 2   ChargerCompany  72856 non-null  int64
 3   Location        72856 non-null  str
 4   ChargerType     72856 non-null  int64
 5   StartDay        72856 non-null  str
 6   StartTime       72856 non-null  str
 7   EndDay          72856 non-null  str
 8   EndTime         72856 non-null  str
 9   StartDatetime   72856 non-null  str
 10  EndDatetime     72856 non-null  str
 11  Duration        72856 non-null  int64
 12  Demand          72856 non-null  float64
dtypes: float64(1), int64(5), str(7)
memory usage: 12.5 MB

In [ ]:
df.duplicated().sum() ##Check duplicate

np.int64(13)

In [10]:
#### View all duplicate rows side by side
df[df.duplicated(keep=False)]

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
28856,329,214,1,public area,0,2022-02-12,7:22:40,2022-02-12,15:44:27,2022-02-12 7:22,2022-02-12 15:44,502,54.34
28857,329,214,1,public area,0,2022-02-12,7:22:40,2022-02-12,15:44:27,2022-02-12 7:22,2022-02-12 15:44,502,54.34
28858,329,214,1,public area,0,2022-02-15,19:29:42,2022-02-15,23:03:11,2022-02-15 19:29,2022-02-15 23:03,213,23.68
28859,329,214,1,public area,0,2022-02-15,19:29:42,2022-02-15,23:03:11,2022-02-15 19:29,2022-02-15 23:03,213,23.68
28861,329,214,1,public area,0,2022-02-17,18:53:55,2022-02-18,3:38:13,2022-02-17 18:53,2022-02-18 3:38,524,58.06
28862,329,214,1,public area,0,2022-02-17,18:53:55,2022-02-18,3:38:13,2022-02-17 18:53,2022-02-18 3:38,524,58.06
40669,461,371,1,apartment,0,2022-02-22,16:17:01,2022-02-22,21:38:44,2022-02-22 16:17,2022-02-22 21:38,322,37.74
40670,461,371,1,apartment,0,2022-02-22,16:17:01,2022-02-22,21:38:44,2022-02-22 16:17,2022-02-22 21:38,322,37.74
51498,276,640,0,company,1,2022-02-26,9:23:02,2022-02-26,10:03:07,2022-02-26 9:23,2022-02-26 10:03,40,15.04
51499,276,640,0,company,1,2022-02-26,9:23:02,2022-02-26,10:03:07,2022-02-26 9:23,2022-02-26 10:03,40,15.04
56652,1956,854,0,public area,1,2022-02-15,6:19:05,2022-02-15,7:36:38,2022-02-15 6:19,2022-02-15 7:36,78,49.07
56653,1956,854,0,public area,1,2022-02-15,6:19:05,2022-02-15,7:36:38,2022-02-15 6:19,2022-02-15 7:36,78,49.07
57315,582,900,0,public parking lot,1,2022-02-24,9:49:03,2022-02-24,10:29:04,2022-02-24 9:49,2022-02-24 10:29,40,18.29
57316,582,900,0,public parking lot,1,2022-02-24,9:49:03,2022-02-24,10:29:04,2022-02-24 9:49,2022-02-24 10:29,40,18.29
60211,228,1045,0,public area,1,2022-02-26,18:24:08,2022-02-26,18:39:59,2022-02-26 18:24,2022-02-26 18:39,16,10.54
60212,228,1045,0,public area,1,2022-02-26,18:24:08,2022-02-26,18:39:59,2022-02-26 18:24,2022-02-26 18:39,16,10.54
61145,615,1094,0,hotel,0,2022-02-05,20:36:57,2022-02-05,22:40:37,2022-02-05 20:36,2022-02-05 22:40,124,13.93
61146,615,1094,0,hotel,0,2022-02-05,20:36:57,2022-02-05,22:40:37,2022-02-05 20:36,2022-02-05 22:40,124,13.93
64957,1146,1341,0,hotel,0,2022-02-04,18:13:23,2022-02-05,1:00:26,2022-02-04 18:13,2022-02-05 1:00,407,32.11
64958,1146,1341,0,hotel,0,2022-02-04,18:13:23,2022-02-05,1:00:26,2022-02-04 18:13,2022-02-05 1:00,407,32.11
66120,156,1450,0,public parking lot,1,2022-02-21,12:03:16,2022-02-21,12:43:16,2022-02-21 12:03,2022-02-21 12:43,40,13.56
66121,156,1450,0,public parking lot,1,2022-02-21,12:03:16,2022-02-21,12:43:16,2022-02-21 12:03,2022-02-21 12:43,40,13.56
71100,1955,2086,0,public area,1,2022-02-24,16:37:14,2022-02-24,16:52:12,2022-02-24 16:37,2022-02-24 16:52,15,7.35
71101,1955,2086,0,public area,1,2022-02-24,16:37:14,2022-02-24,16:52:12,2022-02-24 16:37,2022-02-24 16:52,15,7.35
72779,1858,2605,0,apartment,0,2022-02-27,22:12:35,2022-02-28,4:29:06,2022-02-27 22:12,2022-02-28 4:29,377,22.60
72780,1858,2605,0,apartment,0,2022-02-27,22:12:35,2022-02-28,4:29:06,2022-02-27 22:12,2022-02-28 4:29,377,22.60

In [11]:
#### Drop the duplicates and keep only the first occurrence
df = df.drop_duplicates().reset_index(drop=True)

In [ ]:
#### Ensure no duplicates 
df.duplicated().sum()

np.int64(0)

In [13]:
### Convert date and time columns to datetime objects
df['StartDatetime'] = pd.to_datetime(df['StartDatetime'])
df['EndDatetime'] = pd.to_datetime(df['EndDatetime'])

In [14]:
### Finds all rows where Duration is 0 or negative
invalid_duration = (df['Duration'] <= 0).sum()
print(f"Records with non-positive duration (<= 0): {invalid_duration}")

# 2. Keeps ONLY the rows where Duration is strictly greater than 0 (> 0)
df = df[df['Duration'] > 0].reset_index(drop=True)

Records with non-positive duration (<= 0): 735

In [15]:
print("\n--- Cleaned Data Summary ---")
print(f"Remaining clean records: {len(df)}")
print(df.dtypes)

--- Cleaned Data Summary ---
Remaining clean records: 72108
UserID                     int64
ChargerID                  int64
ChargerCompany             int64
Location                     str
ChargerType                int64
StartDay                     str
StartTime                    str
EndDay                       str
EndTime                      str
StartDatetime     datetime64[us]
EndDatetime       datetime64[us]
Duration                   int64
Demand                   float64
dtype: object

In [16]:
### Save the cleaned dataset ###
df.to_csv('cleaned_charging_records.csv', index=False)
print("\nSaved cleaned dataset as 'cleaned_charging_records.csv'. Step 1 complete!")

Saved cleaned dataset as 'cleaned_charging_records.csv'. Step 1 complete!